image: Visual Studio 2019
configuration: Release

build:
    project: DonDonLibrary.sln

after_build:
    - del DonDonLibrary\bin\Release\*.pdb
    - del ScriptEditor\bin\Release\*.pdb
    - del ConsoleTools\DatabaseEditor\bin\Release\*.pdb
    - 7z a ScriptEditor.zip .\ScriptEditor\bin\Release\*
    - 7z a DatabaseEditor.zip .\ConsoleTools\DatabaseEditor\bin\Release\*
    - move DonDonLibrary\bin\Release\DonDonLibrary.dll DonDonLibrary.dll
    - rmdir /S /Q DonDonLibrary\bin\
    - rmdir /S /Q ScriptEditor\bin\
    - rmdir /S /Q ConsoleTools\DatabaseEditor\bin\

artifacts:
    - path: DonDonLibrary.dll
      name: DonDonLibrary
    - path: ScriptEditor.zip
      name: ScriptEditor
    - path: DatabaseEditor.zip
      name: DatabaseEditor